name: Packag

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create ZIP file
      run: |
        PLUGIN_NAME="dcpleaderboard-plugin"
        VERSION="${GITHUB_REF##*/}"  # Extract tag name from ref
        zip -r "${PLUGIN_NAME}-${VERSION}.zip" "${PLUGIN_NAME}" -x "*.git*" "*.github*" "*.yaml" "infrastructure"

    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        files: dcpleaderboard-plugin.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
